bio/urls.py
from django.conf.urls import patterns, url
from . import views

urlpatterns = patterns('',
	url(r'^$', views.bios_index, name="bios_index"),
	# generic view IndexView:
	# url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
)

eventos/urls.py
from django.conf.urls import patterns, url
from . import views

urlpatterns = patterns('',
	url(r'^$', views.eventos_index, name='eventos_index'),
	# generic IndexView:
	# url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
)

projeto_vyf/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
from filebrowser.sites import site
from artigos import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^blog/', include('blog.urls')),
    (r'^admin/filebrowser/', include(site.urls)),
    (r'^grappelli/', include('grappelli.urls')), # para incluir grappelli
    # pagina simples baseada em request de home
    url(r'^$', 'projeto_vyf.views.home', name='home'),
    # generic view com a classe IndexView:
    # url(r'^$', views.IndexView.as_view(), name='index'),
    #  pagina usando generic views
    # url(r'^$', TemplateView.as_view(template_name="projeto_vyf/index.html")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^artigos/', include('artigos.urls', namespace="artigos")),
    # url(r'^artigos/lista', include('artigos.urls', namespace="artigos_lista")),
    # url(r'^noticias/', include('noticias.urls', namespace="noticias")),
    # url(r'^rss/', include('artigos.urls', namespace="rss")),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^categorias/', include('categorias.urls', namespace="categorias")),
    url(r'^bio/', include('bio.urls', namespace="bio")),
    url(r'^eventos/', include('eventos.urls', namespace="eventos")),
    (r'^comments/', include('django.contrib.comments.urls')),
    # url(r'^categoria/', include('artigos.urls', namespace="index_cat")),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^select2/', include('django_select2.urls')), # para usar o select2
    url(r'^testes/', include('testes.urls', namespace="testes")),
    url(r'^digital/', 'projeto_vyf.views.digital', name='digital')
)

eventos/models.py
# -*- coding: utf-8 -*-
import datetime
from django.db import models
# from datetime import datetime
from datetime import timedelta
from django.utils import timezone
# Create your models here.
from django.core.exceptions import ValidationError

# def validate_data_inicio(value):
#     if value < self.data_inicio:
#         raise ValidationError(u'data errada')


# verificar o erro que ocorre em makemigrations caso a funcao mais_quinze nao esteja fora do class  Evento
def mais_quinze():
    return timezone.now()+timedelta(minutes=15)

class Evento(models.Model):
    titulo = models.CharField(max_length=100)
    data_inicio = models.DateTimeField(u'Data início', default=timezone.now, blank=True)
    # data_inicio = models.DateTimeField(u'Data início', default=datetime.now, blank=True)
    # data_fim = models.DateTimeField(u'Data fim', default=lambda: timezone.now()+timedelta(minutes=15), blank=True)
    
    def mais_quinze():
        return timezone.now()+timedelta(minutes=15)

    data_fim = models.DateTimeField(u'Data fim (mín = 15min)', default=mais_quinze, blank=True)
    # Verificar depois como fica a categoria ou tag
    categoria = models.CharField(max_length=100, null=True)
    texto_simples = models.CharField(max_length=300, null=True)
    texto_maior = models.TextField()
    # Ver o esquema de maps
    local = models.CharField(max_length=300, null=False)
    tag = models.CharField(max_length=150, null=True)
    sub_evento = models.ForeignKey("self", null=True, blank=True)

    def mais_quinze():
        return datetime.now() + timedelta(days = 30)

    def __unicode__(self):
        return self.titulo

    def evento_em_andamento(self):
        agora = timezone.now()
        # agora - datetime.timedelta(days=1)
        return self.data_inicio <= agora <= self.data_fim
    evento_em_andamento.admin_order_field = 'data_inicio'
    evento_em_andamento.boolean = True
    evento_em_andamento.short_description = 'Em andamento?'  

    class Meta:
        ordering = ('-data_inicio',)

    # def erro_data(self):
    #     if self.data_inicio > self.data_fim:
    #         raise ValidationError(u'data errada')
    
    def clean(self):
        conf_data_inicio = self.data_inicio+timedelta(minutes=15)
        if conf_data_inicio > self.data_fim:
            raise ValidationError(u'Erro data início deve ser menor que a data fim, ou fim deve ser maior que início. Duração mínima: 15 minutos!!')
        # if self.data_fim < self.data_inicio:
        #     raise ValidationError('Erro data fim deve ser maior que a data fim.')
        if self.sub_evento is not None:
            if self.data_inicio < self.sub_evento.data_inicio:
                raise ValidationError(u'Erro data inicio sub evento deve ser maior que data inicio evento pai.')
            if self.data_fim > self.sub_evento.data_fim:
                raise ValidationError(u'Erro data fim sub evento deve ser menor que data fim evento pai')

    # def save(self, *args, **kwargs):
    #     if self.sub_evento is not None:
    #         self.data_inicio = max(self.sub_evento.data_inicio, self.data_inicio)
    #         self.data_fim = min(self.sub_evento.data_fim, self.data_fim)
    #         # raise ValidationError("teste")
    #     # if self.data_inicio > self.data_fim:
    #     #     return
    #     super(Evento, self).save(*args, **kwargs)

eventos/views.py
# -*- coding: utf-8 -*-
import datetime
# from datetime import timedelta # << se usar esse import nao precisa datetime.timedelta apentas timedelta
from django.shortcuts import render
from django.views import generic
from .models import Evento
from django.utils import timezone
from categorias.models import Categoria
import calendar

def eventos_index(request):
	eventos_list =  Evento.objects.all().order_by('-data_inicio')
	ano = request.GET.get('ano',)
	mes = request.GET.get('mes',)
	dia = request.GET.get('dia')
	tempo = request.GET.get('tempo',)
	tempoa = request.GET.get('tempoa')

	anos_list = range(2009,2021)
	meses_list = calendar.month_name # << receber mes em texto
	dias_list = range(1,32)
	
	em_andamento = request.GET.get('em_andamento',)

	if ano:
		if ano not in [str(x) for x in range(2009,2051)]:
			#raise ValueError('erro ano')
			ano = timezone.now().year
		eventos_list = eventos_list.filter(data_inicio__year=ano)
	if mes:
		if mes not in [str(x) for x in range(1,13)]:
			mes = timezone.now().month
		eventos_list = eventos_list.filter(data_inicio__month=mes)
	if dia:
		if dia not in [str(x) for x in range(1,32)]:
			dia = timezone.now().day
		eventos_list = eventos_list.filter(data_inicio__day=dia)
	if tempo:
		# try:
		# 	tempot = int(tempo)
		# except ValueError: 
		# 	tempot = 30
		# except OverflowError:
		# 	tempot = 1
		# 	print tempot, type(tempot)
		# except Exception, e:
		# 	raise e
		tempot = tempo

		if tempot not in [str(x) for x in range(0,365)]:
			tempot = 365
			# raise ValueError('Bosta')
		# if tempot not in range(0,31):
		# 	raise ValueError('Foda-se')

		tempox = timezone.now()
		tempoy = tempox+datetime.timedelta(days=tempot)
		eventos_list = eventos_list.filter(data_inicio__range=(tempox,tempoy))
		# eventos_list = eventos_list.filter(data_inicio__range=(timezone.now(),timezone.now()+datetime.timedelta(days=int(tempo))))

	if tempoa:
		tempoa = int(tempoa)
		tempoz = timezone.now()
		tempow = timezone.now()+datetime.timedelta(days=tempoa)
		eventos_list = eventos_list.filter(data_inicio__gte=tempoz)
		eventos_list = eventos_list.filter(data_inicio__lte=tempow)
		# eventos_list = eventos_list.exclude(data_inicio__gte=tempow)

	# if em_andamento:
	# 	eventos_list.evento = 1 #eventos_list.evento_em_andamento()
	# 	eventos_list = eventos_list.filter(evento=1)


	return render(request, 'eventos/index.html',{
		'eventos_list': eventos_list,
		'anos_list': anos_list,
		'meses_list': meses_list,
		'dias_list': dias_list,
		'em_andamento': em_andamento,
		'categorias_list': Categoria.objects.all(),
		})


#  Generic Class View para a lista de eventos:
# class IndexView(generic.ListView):
# 	template_name = 'eventos/index.html'
# 	context_object_name = 'eventos_list'

# 	def get_queryset(self):
# 		return Evento.objects.all().order_by('-data_inicio')[:10]

class DetailView(generic.DetailView):
	model = Evento
	template_name = 'eventos/detail.html'

eventos/templates/eventos/detail.html
{% extends "base.html" %}
{% block content %}


	<h1>{{ evento }}</h1>
	{% if evento.evento_em_andamento %}
		<span class="label label-primary">Evento em andamento</span>
	{% endif %}
	{% if evento.sub_evento %}
		<h2><b>Evento:</b> 
			<a href="{% url 'eventos:detail' evento.sub_evento.id %}"><ul><li>{{ evento.sub_evento }}</a></li></ul></h2>
	{% endif %}
	<p>Categoria: {{ evento.categoria }}</p>
	<h3>Data:</h3>
	<p><b>De</b> {{ evento.data_inicio }} <b>até</b> {{ evento.data_fim }}</p>
	<p>{{ evento.texto_simples }}</p>
	<h3>Informações: </h3>
	<p>{{ evento.texto_maior|safe }}</p>
	<p><b>Local:</b> {{ evento.local }}</p>
	<p><b>Tags:</b> {{ evento.tag }}</p>
		


{% endblock content %}
{% comment %}
	
{% endcomment %}

eventos/templates/eventos/eventos_lista.html
{% if eventos_list %}

	<div class="list-group">
		<a class="list-group-item active" href="#">
			<b>Próximos Eventos:</b>
		</a>
		{% for evento in eventos_list %}
			{% if evento.sub_evento %}
				<a class="list-group-item" href="{% url 'eventos:detail' evento.id %}"><li><b>{{ evento.sub_evento }} </b>- {{ evento }} <font color="gray"> - (Início em: {{ evento.data_inicio }})</li></font></a>
			{% else %}
				<a class="list-group-item" href="{% url 'eventos:detail' evento.id %}"><b>{{ evento }} </b><font color="gray"> - (Início em: {{ evento.data_inicio }})</font></a>	
			{% endif %}
		{% endfor %}
	</div>
	{% else %}
		<p>Nenhum evento disponível</p>
{% endif %}

eventos/templates/eventos/index.html
{% extends "base.html" %}

{% block content %}


	<h1>Eventos</h1>


<div class="btn-group">	
	<button type="button" class="btn btn-default dropdown-toggle" data-toggle = "dropdown" aria-expanded="false">Ano <span class="caret"></span>
	</button>
	<ul class="dropdown-menu" role="menu">
		{% if anos_list %}
			{% for ano in anos_list %}
				<li><a href="?ano={{ ano }}">{{ ano }}</a></li>
			{% endfor %}
	 	{% else %}
			Nenhum ano
		{% endif %}
		
		<li class="divider"></li>
		<li><a href="/eventos">Todos</a></li>
	</ul>
</div>
	
<div class="btn-group">
	<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
	 Mês <span class="caret"></span>
	</button>
	<ul class="dropdown-menu" role="menu">
		{% if meses_list %}
			{% for meses in meses_list %}
				<li><a href="?mes={{ forloop.counter0 }}">{{ meses }}</a></li>
			{% endfor %}
		{% else %}
		<li><a href="#">Nenhuma</a></li>
		{% endif %}
		
		<li class="divider"></li>
		<li><a href="/eventos">Todos</a></li>
	</ul>
</div>

<div class="btn-group">	
	<button type="button" class="btn btn-default dropdown-toggle" data-toggle = "dropdown" aria-expanded="false">Dia <span class="caret"></span>
	</button>
	<ul class="dropdown-menu" role="menu">
		{% if dias_list %}
			{% for dia in dias_list %}
				<li><a href="?dia={{ dia }}">{{ dia }}</a></li>
			{% endfor %}
	 	{% else %}
			Nenhum dia
		{% endif %}
		
		<li class="divider"></li>
		<li><a href="/eventos">Todos</a></li>
	</ul>
</div>


	
<!-- {% for i in "xxxxxxxxxxxx" %} 
	{{ forloop.counter|date:"b" }} 
{% endfor %} -->

	<a href="/eventos"><button type="button" class="btn btn-primary">Todos</button></a>
	<a href="?em_andamento=1"><button type="button" class="btn btn-info">Em andamento</button></a>

	{% if em_andamento %}
		<h3>Em andamento:</h3>
		{% if eventos_list %}
		<table class="table table-condensed">
			<tr>
				<th>Evento</th>
				<th>Data início</th>
				<th>Data fim</th>
				<th>Categoria</th>
				<th>Em andamento</th>
			</tr>
			{% for evento in eventos_list %}
			<tr>
				{% if evento.evento_em_andamento %}
					{% if evento.sub_evento %}
						<td>
							<a href="{% url 'eventos:detail' evento.id %}"><ul><li>{{ evento.sub_evento }} >> {{ evento }}</a></li></ul>
						</td>
					{% else %}
						<td>
							<a href="{% url 'eventos:detail' evento.id %}">{{ evento }}</a>
						</td>
					{% endif %}
					<td>
						{{ evento.data_inicio }}
					</td>
					<td>
						{{ evento.data_fim }}
					</td>
					<td>
						{{ evento.categoria|default:"Nenhum" }}
					</td>
					<td>
						{% if evento.evento_em_andamento %}
							<b>Sim</b>
						{% else %}
							Não
						{% endif %}
					</td>
			<!-- <td>
				{% if  artigo.categoria %}
					{{ artigo.categoria }}	
				{% else %}		
					Nenhum		
				{% endif %}
			</td> -->
				{% endif %}
			</tr>
			{% endfor %}
		</table>
	{% else %}
		<h4><em>* Nenhum evento disponível</em></h4>
	{% endif %}


	{% else %}
	<p> </p>
	{% if eventos_list %}
	<table class="table table-condensed">
		<tr>
			<th>Evento</th>
			<th>Data início</th>
			<th>Data fim</th>
			<th>Categoria</th>
			<th>Em andamento</th>
		</tr>
		{% for evento in eventos_list %}
		<tr>
			{% if evento.sub_evento %}
				<td>
					<a href="{% url 'eventos:detail' evento.id %}"><ul><li>{{ evento.sub_evento }} >> {{ evento }}</a></li></ul>
				</td>
			{% else %}
				<td>
					<a href="{% url 'eventos:detail' evento.id %}">{{ evento }}</a>
				</td>
			{% endif %}
			<td>
				{{ evento.data_inicio }}
			</td>
			<td>
				{{ evento.data_fim }}
			</td>
			<td>
				{{ evento.categoria|default:"Nenhum" }}
			</td>
			<td>
				{% if evento.evento_em_andamento %}
					<b>Sim</b>
				{% else %}
					Não
				{% endif %}
			</td>
			<!-- <td>
				{% if  artigo.categoria %}
					{{ artigo.categoria }}	
				{% else %}		
					Nenhum		
				{% endif %}
			</td> -->
		</tr>
		{% endfor %}
	</table>
	{% else %}
		<h4><em>* Nenhum evento disponível</em></h4>
	{% endif %}

	{% endif %}


{% endblock content %}