bio/urls.py
from django.conf.urls import patterns, url
from . import views

urlpatterns = patterns('',
	url(r'^$', views.bios_index, name="bios_index"),
	# generic view IndexView:
	# url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
)

projeto_vyf/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
from filebrowser.sites import site
from artigos import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^blog/', include('blog.urls')),
    (r'^admin/filebrowser/', include(site.urls)),
    (r'^grappelli/', include('grappelli.urls')), # para incluir grappelli
    # pagina simples baseada em request de home
    url(r'^$', 'projeto_vyf.views.home', name='home'),
    # generic view com a classe IndexView:
    # url(r'^$', views.IndexView.as_view(), name='index'),
    #  pagina usando generic views
    # url(r'^$', TemplateView.as_view(template_name="projeto_vyf/index.html")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^artigos/', include('artigos.urls', namespace="artigos")),
    # url(r'^artigos/lista', include('artigos.urls', namespace="artigos_lista")),
    # url(r'^noticias/', include('noticias.urls', namespace="noticias")),
    # url(r'^rss/', include('artigos.urls', namespace="rss")),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^categorias/', include('categorias.urls', namespace="categorias")),
    url(r'^bio/', include('bio.urls', namespace="bio")),
    url(r'^eventos/', include('eventos.urls', namespace="eventos")),
    (r'^comments/', include('django.contrib.comments.urls')),
    # url(r'^categoria/', include('artigos.urls', namespace="index_cat")),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^select2/', include('django_select2.urls')), # para usar o select2
    url(r'^testes/', include('testes.urls', namespace="testes")),
    url(r'^digital/', 'projeto_vyf.views.digital', name='digital')
)

testes/urls.py
from django.conf.urls import patterns, url
from . import views

urlpatterns = patterns('',
    url(r'^$', views.testes_index, name='testes_index'),
    # url(r'^lista/', views.listing, name='listing'),
    # url(r'^(?P&lt;pk&gt;\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<url_testeid>\d+)/$', views.detail, name='detail'),
)

testes/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.db.models import Q
from datetime import datetime, timedelta
from categorias.models import Categoria
from artigos.models import Artigo
from django.core.exceptions import ValidationError


class Tag(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = 'tags'

    def __unicode__(self):
        return self.name

def limit_publicacao_choices():
    return {'publicacao__lte': datetime.now()}

# def filtros_q():
#     # data_hoje = datetime.now()
#     # data_antes = data_hoje - timedelta(days=190)
#     # testes_in = Teste.objects.all()[:3]
#     # filtro_q = Q(id__in=testes_in) & Q(publicacao__range=(data_antes, data_hoje)) & Q(categoria=6)
#     testes_in = Teste.objects.filter(categoria='6').filter(publicacao__lte=datetime.now()).values_list('id', flat=True)[:3]
#     m = [8]
#     # testes_ex = Teste.objects.filter(id__in=m).values_list('id', flat=True)
#     # n = 'self.relacao_teste'
#     # testes_ex = Teste.objects.filter(id__in=n).values_list('id', flat=True)
#     # testes_ex = list(testes_ex)
#     testes_in = list(testes_in)
#     # testes_in.extend(m)
#     testes_in += m
#     filtro_q = Q(id__in=testes_in)
#     return filtro_q
    
class Teste(models.Model):
    titulo = models.CharField(max_length=100)
    conteudo = models.TextField()
    publicacao = models.DateTimeField('Data de Publicacao', default=datetime.now, blank=True)
    # colocar o default=datetime.now, blank=True para data atual automatica
    categoria = models.ForeignKey(Categoria, null=True, blank=True)
    tags = models.ManyToManyField(Tag, blank=True, null=True)  # To demonstrate select2 multiple
    # tags_2 = models.CharField(Tag, max_length=100, blank=True, null=True)
    # teste_art = models.ManyToManyField(Artigo, blank=True, null=True)

    relacao_teste = models.ManyToManyField('self', blank=True, null=True, symmetrical=False, verbose_name='Testes Relacionados')#, limit_choices_to=filtros_q, help_text=u'Selecione 2 artigos no máximo. ')
    


    # try:
    #     relacao_existente_id = self.relacao_teste.all().values_list('id', flat=True)
    #     print 'veio'
    # except Exception, e:
    #     pass
    # def clean_relacao_teste(self):
    #     relacao_verificar = self.relacao_teste
    #     if len(relacao_verificar) > 2:
            # self.relacao_teste = None
            # return self.relacao_teste
            # raise ValidationError(u'Adicionar no máximo 2 artigos!!')
        # else:
        #     return relacao_verificar

    def __unicode__(self):
        return self.titulo #, self.conteudo, self.publicacao
        # erro ao retornar + de um item em self
    class Meta:
        ordering = ('-publicacao',) # ordena a ordem dos artigos

testes/views.py
from django.http import HttpResponse
# from django.http import HttpResponse, Http404, HttpResponseRedirect, HttpResponsePermanentRedirect
from django.views import generic
from .models import Teste, Tag
from categorias.models import Categoria

from django.shortcuts import render, get_object_or_404, render_to_response
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# class DetailView(generic.DetailView):
#     model = Teste
#     template_name = 'testes/detail.html'

def detail(request, url_testeid):
    db_teste = get_object_or_404(Teste, pk=url_testeid)
    teste_tags = db_teste.tags.all()
    # teste = Teste.objects.get(id=url_testeid)
    categorias_list = Categoria.objects.all()
    return render(request, 'testes/detail.html', {
        'teste': db_teste,
        'teste_tag': teste_tags,
        'categorias_list': Categoria.objects.all(),
        })

def testes_index(request):

    testes_list = Teste.objects.all()
    tag = request.GET.get('tag', ' ').split(',')
    # tag2 = request.GET.get('tag2',)
    categoria = request.GET.get('categoria',0)
    categoria_nome = 0
    tag_nome = None
    # tag = None
    
    if categoria > 0:
        testes_list = testes_list.filter(categoria=categoria)
        categoria_nome = Categoria.objects.get(pk=categoria)

    if len(tag) > 1:
        testes_list = testes_list.filter(tags__in=tag).distinct()
        tag_nome = Tag.objects.filter(id__in=tag).distinct()

    return render(request, 'testes/index.html', {
        'testes_list': testes_list,
        'categorias_list': Categoria.objects.all(),
        'categoria_nome':  categoria_nome,
        'tag_nome': tag_nome,
        # 'tag_nome2': tag_nome2,
        })

# def listing(request):
#     testes_list = Teste.objects.all()
#     paginator = Paginator(testes_list, 5)

#     page = request.GET.get('page')
#     try:
#         testes = paginator.page(page)
#     except PageNotAnInteger:
#         testes = paginator.page(1)
#     except EmptyPage:
#         testes = paginator.page(paginator.num_page)

#     return render_to_response('testes/list.html', {"testes": testes})

testes/templates/testes/detail.html
{% extends "base.html" %}
{% load comments %}
{% block content %}



	<h1>{{ teste }}</h1>

		<h3>Conteúdo:</h3>
		<p>{{ teste.conteudo|safe }}</p>
		<h3>Publicação:</h3>
		<p>{{ teste.publicacao }}</p>
		<h3>Categoria:</h3>
		<p>{{ teste.categoria }}</p>
		
		<h3>Tags:</h3>
		{% if teste_tag %}
			{% for tag in teste_tag %}
				<a href="/testes/?tag={{ tag.id }}">{{ tag }} id: {{ tag.id }}, </a>
			{% endfor %}
		{% else %}
			Nenhuma tag
		{% endif %}
		
		<br><br>
		{% for tag in teste.tags.all %}
			<a href="/testes/?tag={{ tag.id }}">{{ tag }} id: {{ tag.id }}, </a>
		{% endfor %}


		{% if teste.relacao_teste %}
			
		<h3>Relacionados:</h3>
		
		{% for teste_r in teste.relacao_teste.all %}
			<p><a href="/testes/{{ teste_r.id }}">{{ teste_r }} {{ teste_r.id }} - {{ teste_r.publicacao }}</a></p>
		{% endfor %}
	
		{% endif %}
		
		<p></p>

		<select class="js-example-basic-multiple" multiple="multiple" style="width: 300px">
			<option value="AL">Alabama</option>
  			<option value="AU">Aulabama</option>
  			<option value="WY">Wyoming</option>
		</select>

		<p></p>
		<select class="js-example-basic-multiple" multiple="multiple" style="width: 300px">

		{% if categorias_list %}
			{% for categoria in categorias_list %}
				<option value="AL">{{ categoria }}</option>	
			{% endfor %}
		{% endif %}
			<option value="AL">Nenhum</option>
		</select>

		<script>
			$(".js-example-basic-multiple").select2();
		</script>

		<p>Placeholder</p>
		<select class="js-example-placeholder-single" style="width: 300px">
			<option value="AL">Alabama</option>
  			<option value="AU">Aulabama</option>
  			<option value="WY">Wyoming</option>
		</select>

		<script>
			$(".js-example-placeholder-single").select2({
  				placeholder: "Select a state",
  				allowClear: true
			});
		</script>


		<select class="js-data-example-ajax">
  			<option value="select2/select2" selected="selected">select2/select2</option>
		</select>

		<script>
			$(".js-data-example-ajax").select2({
			  ajax: {
			    url: "https://api.github.com/search/repositories",
			    dataType: 'json',
			    delay: 250,
			    data: function (params) {
			      return {
			        q: params.term, // search term
			        page: params.page
			      };
			    },
			    processResults: function (data, page) {
			      // parse the results into the format expected by Select2.
			      // since we are using custom formatting functions we do not need to
			      // alter the remote JSON data
			      return {
			        results: data.items
			      };
			    },
			    cache: true
			  },
			  escapeMarkup: function (markup) { return markup; }, // let our custom formatter work
			  minimumInputLength: 1,
			  templateResult: formatRepo, // omitted for brevity, see the source of this page
			  templateSelection: formatRepoSelection // omitted for brevity, see the source of this page
			});
		</script>


		<h3>Comentários:</h3>
		<div class="well">
			{% get_comment_list for teste as comentarios %}
			{% for comentario in comentarios %}
			<div class="comentario">
				<b>Nome: {{ comentario.name }}<br/></b>
				{% if comentario.url %}URL: {{ comentario.url }}{% endif %}<br/>
				{{ comentario.comment|linebreaks }}
				<hr/>
			</div>
			{% endfor %}
			<h3> Envie um comentário</h3>
			{% render_comment_form for teste %}
		</div>

<p><a href="/testes/">Voltar</a></p>


		

{% endblock content %}
{% comment %}
	
{% endcomment %}

testes/templates/testes/index.html
{% extends "base.html" %}

{% block content %}


	<h1>Testes</h1>

		<select class="js-example-basic-multiple" multiple="multiple" style="width: 300px">

		{% if categorias_list %}
			{% for categoria in categorias_list %}
				<option value="{{ categoria.id }}">{{ categoria }}</option>	
			{% endfor %}
		{% endif %}
			<option value="AL">Nenhum</option>
		</select>

		<script>
			$(".js-example-basic-multiple").select2();
		</script>
	
	<div class="btn-group">
		<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
			Categoria <span class="caret"></span>
		</button>
		<ul class="dropdown-menu" role="menu">
			{% if categorias_list %}
				{% for categoria in categorias_list %}
					<li><a href="?categoria={{ categoria.id }}">{{ categoria }}</a></li>
				{% endfor %}
			{% else %}
			<li><a href="#">Nenhuma</a></li>
			{% endif %}
			
			<li class="divider"></li>
			<li><a href="/testes">Todos</a></li>
		</ul>
	</div>

	<b>Filtro Categoria: </b>{{ categoria_nome.nome|default:"Todas categorias" }}
		
	{% if tag_nome %}
		{% for tag in tag_nome %}
			<a href="/testes/?tag={{ tag_nome.id }}">{{ tag_nome }}</a>
		{% endfor %}
	{% endif %}

	<h3>Postados recentemente:</h3>
	{% if testes_list %}
	<table class="table table-condensed">
		<tr>
			<th>Teste</th>
			<th>Data</th>
			<th>Categoria</th>
		</tr>
		{% for teste in testes_list %}
		<tr>
			<td>
				<a href="{% url 'testes:detail' teste.id %}">{{ teste }}</a>
			</td>
			<td>
				{{ teste.publicacao }}
			</td>
			<td>
				{{ teste.categoria|default:"Nenhum" }}
			</td>
		</tr>
		{% endfor %}
	</table>


	{% else %}
		<h4><em>* Nenhum teste disponível</em></h4>
	{% endif %}

	<div class="alert alert-info" role="alert">
		Tags:
	</div>

{% endblock content %}