bio/urls.py
from django.conf.urls import patterns, url
from . import views

urlpatterns = patterns('',
	url(r'^$', views.bios_index, name="bios_index"),
	# generic view IndexView:
	# url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
)

projeto_vyf/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
from filebrowser.sites import site
from artigos import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^blog/', include('blog.urls')),
    (r'^admin/filebrowser/', include(site.urls)),
    (r'^grappelli/', include('grappelli.urls')), # para incluir grappelli
    # pagina simples baseada em request de home
    url(r'^$', 'projeto_vyf.views.home', name='home'),
    # generic view com a classe IndexView:
    # url(r'^$', views.IndexView.as_view(), name='index'),
    #  pagina usando generic views
    # url(r'^$', TemplateView.as_view(template_name="projeto_vyf/index.html")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^artigos/', include('artigos.urls', namespace="artigos")),
    # url(r'^artigos/lista', include('artigos.urls', namespace="artigos_lista")),
    # url(r'^noticias/', include('noticias.urls', namespace="noticias")),
    # url(r'^rss/', include('artigos.urls', namespace="rss")),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^categorias/', include('categorias.urls', namespace="categorias")),
    url(r'^bio/', include('bio.urls', namespace="bio")),
    url(r'^eventos/', include('eventos.urls', namespace="eventos")),
    (r'^comments/', include('django.contrib.comments.urls')),
    # url(r'^categoria/', include('artigos.urls', namespace="index_cat")),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^select2/', include('django_select2.urls')), # para usar o select2
    url(r'^testes/', include('testes.urls', namespace="testes")),
    url(r'^digital/', 'projeto_vyf.views.digital', name='digital')
)

bio/models.py
from django.db import models
from datetime import datetime
# Create your models here.
from categorias.models import Categoria

class Bio(models.Model):
	nome = models.CharField(max_length=100)
	informacoes = models.TextField()
	publicacao = models.DateTimeField('Data de Publicacao', default=datetime.now, blank=True)
	categoria = models.ForeignKey(Categoria, null=True, blank=True)

	def __unicode__(self):
		return self.nome
	class Meta:
		ordering = ('nome',)

bio/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from .models import Bio
from categorias.models import Categoria
# Create your views here.

#  pode receber parametro categoria=2:
def bios_index (request):
	bios_list = Bio.objects.all()
	categoria = request.GET.get('categoria', 0)
	categoria_nome = 0
	if categoria > 0:
		bios_list = bios_list.filter(categoria=categoria)
		categoria_name = Categoria.objects.get(pk=categoria)
	return render(request, 'bio/index.html',{
		'bio_list' : bios_list,
		'categorias_list' : Categoria.objects.all(),
		'categoria_nome' : categoria_nome,
		})

# class IndexView(generic.ListView):
# 	template_name = 'bio/index.html'
# 	context_object_name = 'bio_list'

# 	def get_queryset(self):
# 		return Bio.objects.all().order_by('nome')[:20]

class DetailView(generic.DetailView):
	model = Bio
	template_name = 'bio/detail.html'

bio/templates/bio/detail.html
{% extends "base.html" %}
{% load comments %}
{% block content %}

<!-- <ul class="nav nav-tabs" role="tablist">
	<li role="presentation">
		<a href="/">Home</a>		
	</li>
	<li role="presentation">
		<a href="/artigos">Artigos</a>		
	</li>		
	<li role="presentation">
		<a href="/noticias">Notícias</a>		
	</li>
	<li role="presentation">
		<a href="/polls">Polls</a>
	</li>
	<li role="presentation">
		<a href="/categorias">Categorias</a>
	</li>
	<li class="active" role="presentation">
		<a href="/bio">Bio</a>
	</li>
</ul> -->

	<h1>{{ bio }}</h1>

		<h3>Informações</h3>
		<p>{{ bio.informacoes|safe }}</p>
		<h3>Publicação:</h3>
		<p>{{ bio.publicacao }}</p>
		<h3>Categoria:</h3>
		<p>{{ bio.categoria }}</p>

		<h3>Comentários:</h3>
		<div class="well">
			{% get_comment_list for bio as comentarios %}
			{% for comentario in comentarios %}
			<div class="comentario">
				<b>Nome: {{ comentario.name }}<br/></b>
				{% if comentario.url %}URL: {{ comentario.url }}{% endif %} <br/>
				{{ comentario.comment|linebreaks }}
				<hr/>
			</div>
			{% endfor %}
			<h3>Envie um comentário</h3>
			{% render_comment_form for bio %}
		</div>

<p><a href="/bio/">Voltar</a></p>

{% endblock content %}
{% comment %}
	
{% endcomment %}

bio/templates/bio/index.html
{% extends "base.html" %}

{% block content %}

<!-- <ul class="nav nav-tabs" role="tablist">
	<li role="presentation">
		<a href="/">Home</a>		
	</li>
	<li role="presentation">
		<a href="/artigos">Artigos</a>		
	</li>		
	<li role="presentation">
		<a href="/noticias">Notícias</a>		
	</li>
	<li role="presentation">
		<a href="/polls">Polls</a>
	</li>
	<li role="presentation">
		<a href="/categorias">Categorias</a>
	</li>
	<li class="active" role="presentation">
		<a href="/bio">Bio</a>
	</li>
</ul> -->

{# <div class=artigo> #}
	<h1>Bio</h1>

	<div class="btn-group">
		<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
			Categoria <span class="caret"></span>
		</button>
		<ul class="dropdown-menu" role="menu">
			{% if categorias_list %}
				{% for categoria in categorias_list %}
					<li><a href="?categoria={{ categoria.id }}">{{ categoria }}</a></li>
				{% endfor %}
			{% else %}
			<li><a href="#">Nenhuma</a></li>
			{% endif %}
			
			<li class="divider"></li>
			<li><a href="/bio">Todos</a></li>
		</ul>
	</div>

	<h3>Biografias:</h3>
	{% if bio_list %}
	<table class="table table-condensed">
		<tr>
			<th>Bio</th>
			<th>Publicacao</th>
			<th>Categoria</th>
		</tr>
		{% for bio in bio_list %}
		<tr>
			<td>
				<a href="{% url 'bio:detail' bio.id %}">{{ bio.nome }}</a>
			</td>
			<td>
				{{ bio.publicacao }}
			</td>
			<td>
				{% if  bio.categoria > 0 %}
					{{ bio.categoria }}	
				{% else %}		
					Nenhum		
				{% endif %}
			</td>
		</tr>
		{% endfor %}
	</table>

<!-- <ul>
		{% for artigo in artigos_list %}
			<li>
				<a href="{% url 'artigos:detail' artigo.id %}">{{ artigo }}</a>
			</li>
		{% endfor %}
	</ul> -->
	{% else %}
		<h4><em>*Nenhum bio disponível</em></h4>
	{% endif %}
{# </div> #}
{% endblock content %}